-- 1. Create Subcategories table
CREATE TABLE swatch_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  name TEXT NOT NULL,
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE swatch_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Manage categories" ON swatch_categories
  FOR ALL USING (auth.uid() = user_id);

-- 2. Add categorization and descriptions to existing Swatches table
ALTER TABLE swatches ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE swatches ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES swatch_categories(id) ON DELETE SET NULL;
