-- Studio North Star: Database Initialization Script
-- Run this in Supabase SQL Editor to prepare for deployment.

-- 1. CREATE TABLES WITH USER_ID OWNERSHIP

-- 🛍️ Shopping Items
CREATE TABLE items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  name TEXT NOT NULL,
  category TEXT,
  price NUMERIC,
  status TEXT DEFAULT 'planning',
  urls TEXT[],
  image TEXT, -- Stores base64 for simpler initial usage
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 🎨 Palette Swatches
CREATE TABLE swatches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  type TEXT NOT NULL, -- 'color' | 'texture'
  name TEXT NOT NULL,
  data TEXT NOT NULL, -- Hex code or image base64
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 🖼️ Inspiration Photos
CREATE TABLE inspo_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  data TEXT NOT NULL, -- High res image base64
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 📂 Scrapbook Boards (Outfit Library)
CREATE TABLE scrapbooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 🧩 Scrapbook Canvas Elements
CREATE TABLE scrapbook_elements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scrapbook_id BIGINT REFERENCES scrapbooks(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  type TEXT NOT NULL,
  content TEXT NOT NULL,
  x NUMERIC DEFAULT 0,
  y NUMERIC DEFAULT 0,
  width NUMERIC DEFAULT 200,
  height NUMERIC DEFAULT 200,
  z_index INT DEFAULT 1
);

-- ✅ Checklist Tasks (Purge Mission)
CREATE TABLE todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  title TEXT NOT NULL,
  description TEXT,
  is_done BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ENABLE ROW LEVEL SECURITY (Ensures users only see their own data)
ALTER TABLE items ENABLE ROW LEVEL SECURITY;
ALTER TABLE swatches ENABLE ROW LEVEL SECURITY;
ALTER TABLE inspo_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE scrapbooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE scrapbook_elements ENABLE ROW LEVEL SECURITY;
ALTER TABLE todos ENABLE ROW LEVEL SECURITY;

-- 3. CREATE POLICIES
-- Generates standard SELECT, INSERT, UPDATE, DELETE policies tied to auth.uid()

CREATE POLICY "Users can CRUD their own items" ON items FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can CRUD their own swatches" ON swatches FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can CRUD their own inspo" ON inspo_photos FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can CRUD their own scrapbooks" ON scrapbooks FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can CRUD their own elements" ON scrapbook_elements FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can CRUD their own todos" ON todos FOR ALL USING (auth.uid() = user_id);
